name: matsci465
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - anyio=4.12.1
  - aom=3.9.1
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attrs=25.4.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - backports.zstd=1.3.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - blosc=1.21.6
  - bokeh=3.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.2.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - c-blosc2=2.15.2
  - ca-certificates=2026.1.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2026.1.4
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.4
  - click=8.3.1
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - colorspacious=1.1.2
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.11.14
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cytoolz=1.1.0
  - dask=2025.12.0
  - dask-core=2025.12.0
  - dask-image=2025.11.0
  - dav1d=1.2.1
  - debugpy=1.8.19
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.4.0
  - distributed=2025.12.0
  - emdfile=0.0.16
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - filelock=3.20.2
  - flexcache=0.3
  - flexparser=0.4
  - fonttools=4.61.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fsspec=2025.12.0
  - gdown=5.2.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.84.4
  - glib-tools=2.84.4
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - h11=0.16.0
  - h2=4.3.0
  - h5py=3.15.1
  - hdf5=1.14.6
  - hdf5plugin=5.1.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - hyperspy=2.3.0
  - hyperspy-base=2.3.0
  - hyperspy-gui-ipywidgets=2.1.0
  - hyperspy-gui-traitsui=2.1.1
  - icu=75.1
  - idna=3.11
  - imagecodecs=2024.9.22
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipympl=0.9.8
  - ipython=9.9.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.8
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - json5=0.13.0
  - jsonpointer=3.0.0
  - jsonschema=4.26.0
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.26.0
  - jupyter-lsp=2.3.0
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.16
  - jxrlib=1.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lazy-loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.11.0
  - libclang-cpp17=17.0.6
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcurl=8.18.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libgoogle-cloud=2.31.0
  - libgoogle-cloud-storage=2.31.0
  - libgrpc=1.67.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - liblapack=3.11.0
  - libllvm17=17.0.6
  - libllvm19=19.1.7
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopus=1.6
  - libparquet=18.1.0
  - libpng=1.6.53
  - libpq=17.7
  - libprotobuf=5.28.2
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.9.0
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - link-traits=1.0.3
  - llvm-openmp=21.1.8
  - llvmlite=0.46.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mistune=3.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpire=2.10.2
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - munkres=1.1.4
  - narwhals=2.15.0
  - natsort=8.4.0
  - nbclient=0.10.4
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncempy=1.14
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - notebook-shim=0.2.4
  - nspr=4.38
  - nss=3.118
  - numba=0.63.1
  - numexpr=2.14.1
  - numpy=2.3.5
  - openjpeg=2.5.3
  - openldap=2.6.10
  - openssl=3.6.0
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - partd=1.4.2
  - pcre2=10.46
  - pentapy=1.4.1
  - pexpect=4.9.0
  - pillow=11.3.0
  - pims=0.7
  - pint=0.25.2
  - pip=25.3
  - platformdirs=4.5.1
  - ply=3.11
  - pooch=1.8.2
  - prettytable=3.17.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py4dstem=0.14.14
  - pyaml=25.7.0
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pybaselines=1.2.1
  - pycparser=2.22
  - pyface=8.0.0
  - pygments=2.19.2
  - pylops=2.6.0
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pyparsing=3.3.1
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pysocks=1.7.1
  - python=3.11.11
  - python-box=7.3.2
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt-main=5.15.15
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rosettasciio-base=0.12.0
  - rpds-py=0.30.0
  - ruamel.yaml=0.19.1
  - ruamel.yaml.clib=0.2.15
  - scikit-image=0.26.0
  - scikit-learn=1.8.0
  - scikit-optimize=0.10.2
  - scipy=1.16.3
  - send2trash=2.0.0
  - setuptools=80.9.0
  - sip=6.15.0
  - six=1.17.0
  - slicerator=1.1.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8.1
  - sqlite=3.51.1
  - stack_data=0.6.3
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tblib=3.2.2
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tifffile=2024.12.12
  - tinycss2=1.5.1
  - tk=8.6.15
  - toml=0.10.2
  - tomli=2.3.0
  - toolz=1.1.0
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traits=7.1.0
  - traitsui=8.0.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.6.3
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstd=1.5.7
prefix: /opt/anaconda3/envs/matsci465
